on:
  schedule:
    - cron: '0 11 * * *'

jobs:
  renovate:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/renovatebot/renovate:37
      env:
        RENOVATE_PLATFORM: github
        RENOVATE_TOKEN: ${{ secrets.RENOVATE_TOKEN }}
        RENOVATE_REPOSITORIES: '["intermission-renovate/flutter-pub"]'
        LOG_LEVEL: debug
    steps:
      - name: Run renovate
        run: renovate